### PR TITLE
CY-3436 Add tenant name to cfy agents commands

### PR DESCRIPTION
**Pull request by YoniItzhak**

### CODE REVIEW

**Comment by YoniItzhak** [comment]
This PR serves a few objectives:
1. Adding `tenant-name` to `cfy agents list`, enabling users to list agents of a specific deployment. 
2. Logging `Explicitly using tenant <tenant-name>` in case of using `cfy agents <validate, install, list> --tenant-name <tenant-name>` command. This will make the code more explicit and prevent confusion of whether the tenant-name is in use or not (like happened to me).

**Comment by geokala** [comment]
Do you mean "enabling users to list agents of a specific tenant" or do you mean that you added --deployment to cfy agents list?

**Review by geokala — APPROVED** [review]

**Review by geokala — CHANGES_REQUESTED** [review]
As pointed out in chat by @tehasdf , tenant name should probably be used (I assumed the decorator was doing something magic).

**Review by geokala — APPROVED** [review]
OK, apparently the pass_client decorator handles this in some way, so approving again.

**Pull request merged**
