### PR TITLE
Extended "cfy executions cancel" to include support for cancelling by deployment Id

### PR DESCRIPTION
**Pull request by 01000101**
It's annoying to have to track down an exact execution Id to cancel an execution. It's much easier to pass in a deployment Id (like the majority of other commands) and have any running execution cancelled for the deployment Id.  Now users can specify "-d" to the cancel operation as well as keeping the "-e" option.

### CODE REVIEW

**Comment by idanmo** [comment]
Hi there!
Thanks for your contribution!
We are checking whether this API conflicts with upcoming improvements we're planning for the CLI.

**Comment by isaac-s** [comment]
@idanmo ping

**Comment by 01000101** [comment]
Would have loved to see this in 3.3 but I guess it hasn't made the cut yet. Already missing the functionality

**Comment by idanmo** [comment]
Hi,
We're planning a bunch of improvements in CLI which would hopefully be released in 3.4.
We'll definitely look into your suggestion once we'll start working on it.
Thanks!

**Comment by geokala** [comment]
Closed: As this PR is more than six months old without having been merged. Please reopen (and rebase if necessary) if it is still relevant.

**Pull request closed without merging**
