### PR TITLE
Upgrade & loosen fabric dependency

### PR DESCRIPTION
**Pull request by funkyHat**
currently clashing with cloudify-fabric-plugin

### CODE REVIEW

**Comment by idanmo** [comment]
This PR cannot be merged as it breaks the CLI packages build process.
We have previously tried to upgrade and it was too hard getting omnibus to work with a newer version of Fabric.

**Comment by funkyHat** [comment]
Oh dear :( this means the cli is incompatible with the latest `cloudify-fabric-plugin`...

**Comment by funkyHat** [comment]
Could it be `>=1.8.3` instead (assuming there's some way to pin the version in omnibus outside of setup.py)?

**Comment by idanmo** [comment]
The problem was that a newer fabric version requires and newer version of libffi.
After investigating this a little, a newer pip version used when building with omnibus should solve the problem as it bundles all the required dependencies within the final package.
I couldn't find an easy way to specify the latest pip version in omnibus so perhaps you can try yourself..

**Comment by funkyHat** [comment]
I think this should do it

**Comment by funkyHat** [comment]
This was fixed in #631 instead

**Pull request closed without merging**
